### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by ewilazarus** [emgucv/emgucv#1]
Is it compatible with .NET Core?

**Comment by emgucv** [comment]
It is not compatible with .NET Core.
 
For some reason, we are not able to build even a .Net Core project from the template either in VS2015 Update 3 or VS2017 RC. We tried .Net Console application, .Net Core library and .Net Core UnitTest. None of the projects can be build after created from template. (with various reason ranging from Nuget Error to "Project file does not exist" build error even when the project loaded successfully. A little bit disappointed with Visual Studio.

Well, .Net Core is still in preview so I am hoping that we can get an Hello World program to build once VS2017 final release is out. Then we can start to consider adding support to .Net Core.

For now, we will use Windows Form for Windows Desktop, Xamarin Mac for Mac and Mono for Linux.

**Comment by hismichael** [comment]
What's the status of the .NetCore compatibility now?

**Comment by GabrielTK** [comment]
+1 for .NET Core. Using a "wrapper" on my project At the Moment.

**Comment by bernd5** [comment]
Hi Garbiel,
is it possible to share your wrapper with us?
I sent some suggestions to make multi-platform support easer, but it's closed now: https://github.com/emgucv/emgucv/issues/17.

regards,

Bernd

**Comment by jeremejevs** [comment]
@emgucv [.NET Core 2](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/) is out, with a ton of previously missing APIs. Visual Studio 2017 has been released back in March too. Could you, please, give it another go and see if Emgu is Core-ready?

**Comment by bernd5** [comment]
Hi I ported emguCV to .net standard 1.4 (I created a pull request) - so it should run with net core...

**Comment by goodtogood** [comment]
.net core 2.0 is released ,is there some plan?

**Comment by PArpad** [comment]
Hi!

I've succesfully built and ran the hello-world app of EmguCV for .Net Core 2.0, however i can't use anything which has System.Drawing referenced. Is there a way to work around this right now?

**Comment by berndb5** [comment]
Hi,
System.Drawing does not exist (or most of it) in .NetStandard and .NetCore. 
Especially System.Drawing.Bitmap which is very Windows specific does not exist in System.Drawing...
What do want?

**Comment by PArpad** [comment]
Hi!
I wanted to use EmguCV with .Net Core 2.0 on a Raspberry Pi, to process the images from the camera module. But it seems to be unlikely to make it work sadly.

**Comment by berndb5** [comment]
Hi,
what does not work? How do you use the code for .net core 2.0?

**Comment by PArpad** [comment]
Hi!

My problem is double sided. 
Firstly: I made the following test app:
```
using Emgu.CV;
using Emgu.CV.CvEnum;
using Emgu.CV.Structure;
using System;
using System.Drawing;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            Mat img = new Mat(200, 400, DepthType.Cv8U, 3);
            img.Save("saved.jpg");
        }
    }
}
```

My .csproj is:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="3.2.0.2721" />
  </ItemGroup>

  <ItemGroup>
    <None Update="concrt140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="cvextern.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="msvcp140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="opencv_ffmpeg320_64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="vcruntime140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

When i try to run it, on my laptop(windows 10, visual studio 2017), i get the following exception(at saveing the image):

> {System.TypeLoadException: Could not load type 'System.Drawing.Bitmap' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>    at Emgu.CV.Mat.Save(String fileName)
>    at ConsoleApp3.Program.Main(String[] args) in C:\Users\Arpi\Documents\Visual Studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 14}

Secondly: If i get rid of the save, then it can run properly on my laptop. But as soon as i publish it to my raspberry pi, i get this exception:

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'Emgu.CV.MatInvoke' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'cvextern': The specified module or one of its dependencies could not be found.

Getting this while the dll-s are are in the directory of the executable.

Sorry if my questions are really basic, i'm relatively new to EmguCV, and not sure about its possibilities.

Thanks:
Arpad

**Comment by berndb5** [comment]
Hi Arpad,

unfortunately the current nuget package contains only the .NETFramework IL-Code and the native windows binaries.

To run your application on .NetCore you need a custom build.
The reason for that is, that the code itself has many compile switches which enables or disables platform specifc things like System.Drawing.Bitmap for .NET-Framework (it does not exist in .NETCore).

Because I wanted to run emguCV on .NETCore as well, I porteted it to .NETStandard 1.4 (to build it for .NETStandard the compiler switch NETSTANDARD1_4 must be defined).

To run your app you on .NetCore you can check out the source code from github and include the Emgu.CV project (it is a shared project) and define the Compiler switch NETSTANDARD1_4.

In addition you need some native code which is written in C++ and must be compiled for you platform as well.
When you checkout the project you can find some bat-files which do the build job (e.g. you should build the code for Linux).
Or you can search the emguCV website - perhaps they have some prebuilt binaries.

The error you mentioned on your raspberry pi says that it can not find the native code.

Kind regards,

Bernd

**Comment by PArpad** [comment]
Hi Bernd!

So if i understand correctly, my method didn't work because i have to compile and build the emgucv library on my target machine, and with the NETSTANDARD1_4 switch), and if thats successful, i may be able to use it.

> the code itself has many compile switches which enables or disables platform specifc things like System.Drawing.Bitmap for .NET-Framework (it does not exist in .NETCore).

Becasue of this i won't be able to use any function in emgucv, which requires System.Drawing, right?

Thanks for the clarifications:
Arpad

**Comment by berndb5** [comment]
Hi Arpad,
yes, that's true - but it is not only System.Drawing - there is much more like Serialization, Dll-Loading...

The managed code you do really not need to build, you can just add a reference (the compiled code is added to your managed binary).

But you need a compatible binary for the native part (OpenCV) - on Windows it is cvextern.dll.

regards,


Bernd

**Comment by rymnikski** [comment]
Hi guys,
How is going this migration? Exist a branch with the current work made? 
I will like to help to port this awesome wrapper.

cheers.

**Comment by mcline007** [comment]
Any traction on this?..... 
Anywhere I can download a emgu dlll compatible with dotnet core or dotnet standard?

**Comment by emgucv** [comment]
With the merged pull request #47 from berndb5 you are able to compile Emgu CV with .NET standard 1.4 profile with the current development code.  Just follows the compile from source steps from 
http://www.emgu.com/wiki/index.php/Download_And_Installation#64-Bit_Windows
And open "Solution\Windows.Desktop\Emgu.CV.sln" with Visual Studio, compiles the "Emgu.CV.World.NetStandard1_4" project and you will have a .NET standard 1.4 profile Emgu.CV.World.dll.

.NET standard 1.4 profile is compatible with .NET Core 1.0 and .NET Core 2.0

Please note that you will also need to compile the native Open CV library on your selected platform because Emgu CV dll depends on Open CV.

**Comment by MaikuMori** [comment]
What's missing to get this working with NuGet?

**Comment by gerardo-lijs** [comment]
Just wanted to mention this blog with alternatives for System.Drawing in .NET Core that will probably help porting EmGu to .NET Core:

https://blogs.msdn.microsoft.com/dotnet/2017/01/19/net-core-image-processing/

**Comment by ricardomga** [comment]
It would be realy great to see this ported to .NET Core

**Comment by tomsfernandez** [comment]
hi guys, any updates on this?

**Comment by havefunbb** [comment]
hi guys, any updates on this?

**Comment by vadash** [comment]
> It would be realy great to see this ported to .NET Core

If u follow guide above u will get working libs. Just need to adapt few places for new code. Example below
`
        public bool SetImage(Bitmap bitmap)
        {
            BitmapData data = null;
            try
            {
                data = bitmap.LockBits(new Rectangle(0, 0, bitmap.Width, bitmap.Height),
                    ImageLockMode.ReadWrite,
                    bitmap.PixelFormat);
                ImageCv = new Image<Bgra, byte>(bitmap.Width, bitmap.Height, data.Stride, data.Scan0);
            }
            finally
            {
                bitmap.UnlockBits(data);
            }
            return true;
        }
`

**Comment by MaikuMori** [comment]
I think what people are looking for is working NuGet package which has builds for both .NET Standard/Core and .NET Framework. Especially since Microsoft is committed to making .NET Standard the main specification while still supporting .NET Framework at slower pace.

**Comment by gerardo-lijs** [comment]
I've been using Emgu for a few years with great results. Unfortunately it looks like right now it's a little bit behind of the last OpenCV and also it lacks direct NuGet package targeting .NET Standard. The last week I installed in a new WPF project using .NET Core 3, OpenCVSharp and it worked perfectly right after installing.

I'm not complaining about OSS nor the project, the work the collaborators do it's remarkable but I'm afraid that if Emgu doesn't keep up people might change in the future.

Let me know if there is any part of the project I can help with or if you know something about what's the idea with the future of Emgu

**Comment by kamilk91** [comment]
Any official news in that thread? Nobody wants to use Azure and Google and Amazon, we want to warm our private processors @emgucv !!! ;-)

**Comment by shanselman** [comment]
How close is this? What help is needed?

**Comment by ericstj** [comment]
Took a look at the latest package and the discussion in this thread and I see the following path forward.

1. Add your netstandard1.4 library under lib/netstandard1.4 in the package.
2. Move your native assets to runtimes/win-<arch>/native, and make sure you're build-targets pick up the files from this location.  Disable inclusion into None if SDK 
is already raising the assets to items https://github.com/emgucv/emgucv/blob/f52f97faa4f879d8af5ac16bb017f6ec223a861c/platforms/nuget/Emgu.CV.targets#L14-L25
Here's an example of another project which does this: https://github.com/dotnet/machinelearning/blob/master/pkg/common/CommonPackage.props
3. When installed in .NETCore projects you can disable the errors here since .NETCore can handle runtime-native-asset selection.  Document to your users that they need to bring their own OpenCV on platforms that aren't explicitly supported by your package.
https://github.com/emgucv/emgucv/blob/f52f97faa4f879d8af5ac16bb017f6ec223a861c/platforms/nuget/Emgu.CV.targets#L27-L29

I think that's the work to move forward using what's already being built today / exists in this repository.

I think there is likely a separate issue around how to deal with OpenCV cross-platform. @gerardo-lijs brought up the fact that there's another project which builds a copy of OpenCV and redistributes it.  That's one option: emgucv can build OpenCV for more platforms and redistribute the dependency.  Another option would be to get the OpenCV maintainers to publish a binary redistributable (and ideally nuget packages).  We faced a similar problem in ML.NET with tensorflow, and it may be a decent template to follow if you have to do the packaging for OpenCV yourself: https://www.nuget.org/packages/Microsoft.ML.TensorFlow.Redist/.  Building your own copy can be challenging since you have to get the dependencies right to make it work across many distros.  There are some folks who did this work for dotnet projects that I can connect you with if that is the route you go down.

**Comment by emgucv** [comment]
The dotnet standard compatible binary is included in the official release as an experimental support. 
We do not want to officially support it at this moment, especially not for the nuget pacakge. The step moving forward is to advise user that they need to include the native binary on top of the managed .net standard dll deployed, in order to run the dotnet standard dll on different platforms. 
e.g. There would be user trying to run it on Android or iOS or Raspberry pi devices, the managed code will not be able to find the native components, in which case, Emgu CV should raise an exception with the corresponding error message.
If we officially put it in the nuget release and said we support net standard, our user will try to use it on platforms supporting .net standard without deploying the native components, find that it doesn't work, and simply complains Emgu CV doesn't work and we will have lots of negative feedback. We are thinking about raising an exception message that tell user when they need to get/build the native component. The current issues is that we cannot identify the running platforms in dot net standard to provide platform specific error message, unless we use the platform detection library code from Xamarin Forms. e.g. Dot net standard do not have native support to tell if you are running on Android or iOS. And we certainly do not want to have Xamarin Forms as a dependencies just because we want platform detection code....

We are keeping an eyes on this issue and we are actively looking in to support dot net standard. The development path is to raise the right exception to the user when the native component is missing.

**Comment by ericstj** [comment]
> the current issues is that we cannot identify the running platforms in dot net standard to provide platform specific error message, 

Have you considered [RuntimeInformation.OSDescription](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.osdescription?view=netframework-4.8#System_Runtime_InteropServices_RuntimeInformation_OSDescription)?

**Comment by emgucv** [comment]
RuntimeInformation.OSDescription is pretty useless by itself alone. It reports: "Unix 4.4.124.0" on Android emulator and also reports "Unix 18.6.0.0" on my Mac OS.

**Comment by ericstj** [comment]
That doesn't sound right, at least not on .NETCore.  We back this value with UName so it should have a reasonable value on mac. 
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Native/Unix/System.Native/pal_runtimeinformation.c#L30

@akoeplinger this looks like Mono / xamarin is not giving a good value:
https://github.com/mono/mono/blob/c239906a0177a69417f021e4bd2702b179b68454/mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs#L144
https://github.com/mono/mono/blob/c239906a0177a69417f021e4bd2702b179b68454/mcs/class/corlib/System/OperatingSystem.cs#L98-L138

Assuming this is fixed, is that the only blocker for doing the work to publish a netstandard version?  I think there are other ways of getting a reasonable error message.  You can tell the users that EmguCV requires the platform to provide a copy of OpenCV and you couldn't find one.  That's not necessarily a statement about what platform you're running on, but a statement of the environment/application.

**Comment by akoeplinger** [comment]
@ericstj I agree we could give a better value for OSDescription but an explicit design goal of that property was to not be parsed for finding out which platform you're on.

That's what `OSPlatform / IsOSPlatform()` was supposed to enable but unfortunately it's not really useful yet for Xamarin platforms: https://github.com/dotnet/corefx/issues/27417

What I see our users do for the case of potentially missing native libraries is to catch the `DllNotFoundException` and provide an error message.

**Comment by ericstj** [comment]
> OSDescription but an explicit design goal of that property was to not be parsed for finding out which platform you're on.
> DllNotFoundException on the pinvoke call and provide an error message.

Right, I believe @emgucv just wants to use it for a useful exception message, they'd like to include `OSDescription`  and have it be something meaningful.

**Comment by akoeplinger** [comment]
Yeah I agree, filed https://github.com/mono/mono/issues/15494 to keep track of it.

**Comment by ForteUnited** [comment]
Hi guys. Its no 8/23/2019 and am wondering if emgu.cv works with .net core. I'm guessing no but holding out hope..... 
Thanks!

**Comment by emgucv** [comment]
See the comment here:
https://github.com/emgucv/emgucv/issues/1#issuecomment-501009306

> The dotnet standard compatible binary is included in the official release as an experimental support.

**Comment by virzak** [comment]
@emgucv would you consider putting it on nuget or myget as a prerelease?

**Comment by MaikuMori** [comment]
From my experience trying to get emgucv to work on core, especially on other platforms is just not worth the hassle. At least at this stage.

Interest from Scott Hanselman and Eric StJohn gave me hope, but nothing much happened so far from emgucv side.

**Comment by ForteUnited** [comment]
Good to know. I'll pivot and look at just doing what I need to do in python and django or something.

Thanks!

**Comment by emgucv** [comment]
@virzak Creating nuget package for the .Net Core is on our todo list. 

There are still a lots of pieces need to be solved. Particularly on how the unmanaged library can be deployed. 

The plan is to have an Emgu.CV.Core nuget package that support .net standard, but will also need separate Emgu.CV.Platform.Runtime package for each of the supported platform that bundle the native runtime. In an ideal implementation, the Emgu.CV.Core nuget package should tell which package to download at runtime if it find that the native open cv library is missing. 

Releasing the Emgu.CV.Core nuget package without having the runtime components (the native open cv library for each of the individual platform) doesn't make sense at this moment.

**Comment by terrajobst** [comment]
@emgucv

I've run [API Port](https://github.com/Microsoft/dotnet-apiport) on your latest NuGet package. The UI of course only works on .NET Core 3.0 (not .NET Standard). Your lower level assembly only misses these WCF APIs. I’ve got no idea how hard it is to replace them.
 
* `System.ServiceModel.InstanceContextMode`
* `System.ServiceModel.ServiceBehaviorAttribute`
* `System.ServiceModel.Dispatcher.ExceptionHandler`

@mconnew might have some suggestions on how to replace them.

As @ericstj has pointed out, the biggest challenge will be to bundle the native versions of OpenCV for all the operating systems. NuGet has support for that on .NET Core, but you'll have to build them (which you usually can't from Windows, so your build has to be done from multiple machines).

However, it seems to me that as a reasonable starting you could support .NET Core only Windows and then add other platforms as you get feedback. macOS is probably relatively easy (because the OS ABI is very stable). Providing a binary for all the flavors of Linux/Unix might be harder, but a reasonable starting could be that you don't provide the binary and people on those platforms have to built it themselves and deploy it next to their app -- that sounds horrible, but it is somewhat inline with the experience on those platforms. Long term, I'd hope that we can provide a better experience for source-based distribution and acquisition into NuGet but that doesn't exist today.

If you're interested we can setup a conf call with you, @ericstj, and me. We believe we have all the pieces available to make you successful on .NET Core. But our written guidance is a bit shallow right now 😄

**Comment by virzak** [comment]
Hi @emgucv,

Any PRs I can submit for this .Net Core to happen? Would love to help out. Feel free to contact me at first.last@gmail.com.

**Comment by virzak** [comment]
Hi all,

Working on [PR](https://github.com/emgucv/emgucv/pull/275) to convert this to .Net Core.
This is still in the very early stages, but Emgu.CV.World and Emgu.CV.UI are now converted to .Net Core. Nuget packages are published [here](https://github.com/virzak/emgucv/releases/tag/4.1.3.alpha.0).

Zedgraph dependency also had to be ported to .Net Core. The PR is [here](https://github.com/ZedGraph/ZedGraph/pull/16).

This is work in progress, but would like some early feedback from the community.

Converting the tests and examples next.

**Comment by terrajobst** [comment]
Just took a quick look at your PR. It seems quite reasonable to me. Most of it is noise from moving to SDK-style projects in order to multi-target and to accommodate the naming conflict between the BCL `Range` and `Emgu`s Range. Sorry about that.

The maintainers have to decide whether they want to target .NET Core directly or whether they want to provide a .NET Standard version instead. I think the .NET Core dependency doesn't seem unreasonable to me; in the end it seems part of the component will have to provide a .NET Core specific artifact anyway in order to expose the UI dependencies, which you won't be able to do in .NET Standard. So I'd see this a click stop towards more portability.

**Comment by emgucv** [comment]
Closing ticket now. 

The current 4.5.1 release is based on .Net Standard 2.0 and is fully compatible with .Net Core 2.0
