### ISSUE TITLE
Exception when using Sticher with Cuda, EmguCv versions 3.0 and 3.3

### ISSUE THREAD

**Issue by IliaBa** [emgucv/emgucv#102]
Hello,

Tryed to use the Sticher with Cuda enhancements to check the performance but keep getting exception:

Installed Cuda - 9.1(latest)
EmguCv - 3.3.0.2826(commercial) and 3.0.0.2158(commercial) 

Exception Message: 
Emgu.CV.Util.CvException: OpenCV: You should explicitly call download method for cuda::GpuMat object.

Logfiles attached.
[SticherExceptionEmguCv_v3.3.txt](https://github.com/emgucv/emgucv/files/1766837/SticherExceptionEmguCv_v3.3.txt)
[SticherExceptionEmguCv_v3.0.txt](https://github.com/emgucv/emgucv/files/1766838/SticherExceptionEmguCv_v3.0.txt)

Found this isssue https://github.com/opencv/opencv/issues/6231 on the net, maybe it is related?

Thanks in advance.
Ilia.

**Comment by emgucv** [comment]
This issue is actually two folded:
1. In the 3.3 release, Open CV's default build is to disable "NONFREE" components, including GPU SURF. For stitching, the GPU stitcher use GPU SURF, using the default build flags with Open CV, our commercial build omitted "NONFREE" components and the Stitcher will not be able to use GPU mode.
2. If we perform a custom build, enabling the NONFREE component and build with GPU, which we have tried. It will also fail due to the the said open cv issue.

**Comment by IliaBa** [comment]
Hi,

So basically you are saying that the issue is derived from the original opencv source code?
Can you fix this in EmguCV?

Thanks.

**Comment by emgucv** [comment]
Our official release will try to follow the same build flags used in Open CV. You can enable "NONFREE" components by building from source. Instructions can be found here:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git
You can turn the "OPENCV_ENABLE_NONFREE" to "ON" to enable the nonfree component.

**Comment by emgucv** [comment]
Closing issue now.
