### ISSUE TITLE
FindTransformECC NaN encountered

### ISSUE THREAD

**Issue by lucysvob** [emgucv/emgucv#120]
Hello,
I described one possible issue on stackoverflow, but nobody answered me:
https://stackoverflow.com/questions/49671858/c-sharp-emgu-findtransformecc-nan-encountered
I am not sure if it is bug or if it is just my mistake. Could you please test this function.
Thank you,

Lucie

**Comment by Callum-Shipton** [comment]
Total guess, but I think when you pass to FindTransormECC an initialized matrix, it uses that as a first guess at the transformation. However since you've initialized it with default values it will be full of zeros, which i'm guessing is why it's getting the NaN. Could you try initializing the matrix to the identity? {[1, 0, 0],[0, 1, 0]}

**Comment by lucysvob** [comment]
Cool, Thank you very much for the help. It helped to init values to what you described:

'''
float[,,] warp_matrix_temp = new float[2, 3, 1] { { { 1 }, { 0 }, { 0 } }, { { 0 },  { 1 }, { 0 } } };
'''
I will forward this answer to stackoverflow. It sould be good to write it to docs.
Thank you,

Lucie
