### ISSUE TITLE
Upgrade ZedGraph Version 6 (.NET Core)

### ISSUE THREAD

**Issue by Theoistic** [emgucv/emgucv#267]
Noticed that ZedGraph 6 preview is out, which is compatible with .net core / .net standard.
if that is the only thing holding .net core compatible .. an upgrade would be a feature request.

as mentioned in #79

**Comment by dzarda** [comment]
More like remove the dependency altogether

**Comment by NLI-KelbyHunt** [comment]
Any news on this issue?

**Comment by emgucv** [comment]
ZedGraph is not holding back .net core compatibility. We already provided an experimental build in our 4.x that supports .Netstandard 1.1 profile, which also support .Net Core. 
In the next release, we will have an Emgu CV nuget package with .Netstandard 2.0 profile, and a Emgu CV Windows runtime package that contains Emgu.CV.UI.dll, the native windows runtime and the dependency on ZedGraph. We will keep using the stable version of ZedGraph and will not move to ZedGraph 6 until it becomes stable.

**Comment by NLI-KelbyHunt** [comment]
@emgucv Thank you for your prompt response. We are excited to see the next release of Emgu.CV as a NuGet release.

We had a hard push to convert to .NET Core 3.0/3.1 in all our GUI's. In the current release of Emgu.CV, a .NET Core 3.0/3.1 WPF/WinForms application will not compile due to the dependency on `ZedGraph 5.1.7` having no compatible framework versions.

As a licensed user, do we have access to an experimental NuGet feed by chance? Or should we just wait? Sounds like it isn't that far off.

**Comment by emgucv** [comment]
The Emgu CV 4.2.0 nuget packages now support .net standard 2.0:
https://www.nuget.org/packages/Emgu.CV.runtime.windows/
https://www.nuget.org/packages/Emgu.CV/
It no longer depends on ZedGraph for .net standard 2.0 compatible projects.

**Comment by emgucv** [comment]
This commit removed ZedGraph depenedency from Emgu.CV.UI. 
https://github.com/emgucv/emgucv/commit/a70c5582cf8e604c3ec8d904532e48e74a69a6fb
Emgu.CV no longer depends on ZedGraph. 

Closing ticket now.
