### ISSUE TITLE
EmguCV-4.2.0.3636 Setup Error

### ISSUE THREAD

**Issue by chungyau97** [emgucv/emgucv#293]
**Visual Studio 2013 - .Net Framework v4.6.1**
I'm new to EmguCV. based on EmguCv Wiki and Youtube tutorial I came to some trouble to import library. 

**Steps on what I did: Error**
- Downloaded and installed **'libemgucv-windesktop-4.2.0.3636.exe'**. 
- Add reference to my project **'Emgu.CV.World.Netstandard.dll'** from **'bin'** Folder.
- Add existing items to my project EVERYTHING in **'\libs\x64'**.

**Picture for illustration:**
![image](https://user-images.githubusercontent.com/33013947/73521829-f90a8280-4441-11ea-93d9-1086607c0ac0.png)

**Another Error in NuGet Package**
![image](https://user-images.githubusercontent.com/33013947/73522946-b4341b00-4444-11ea-9fd8-88e4e7f20883.png)

**What should I do to ix above errors?**

**Mix and Match Steps: Success**
- Download **'libemgucv-windesktop-4.1.1.3497'**.
- Use **'Emgu.CV.World.dll'**

Can anyone explain why there's no **'Emgu.CV.World.dll' in 'libemgucv-windesktop-4.2.0.3636.exe'**? 
I wonder what's the difference between **CUDA and NON-CUDA version?**
I **don't have GPU** in my work laptop can I still **use the CUDA version** by **importing EVERYTHING '\bin\x64'**?

**Comment by emgucv** [comment]
We have a development build that fixed this issue. Please email us supprt@emgu.com and we will reply with the dev build for you to test with.

We will update the Asset in Unity store soon.

**Comment by emgucv** [comment]
There is a CUDA version that will only work if you have a NVidia GPU installed. The native binary depends on the nvidia graphic driver and will crash on any workstation that do not have Nvidia driver installed due to missing dependency. 
If you have a NVidia graphic card on the workstation, you should install the following nuget packages instead:

https://www.nuget.org/packages/Emgu.CV.runtime.windows.cuda/
https://www.nuget.org/packages/Emgu.CV/

**Comment by emgucv** [comment]
Closing ticket now
