### ISSUE TITLE
dotnet publish single file fails during app startup in .net 5 on Windows 

### ISSUE THREAD

**Issue by JohnTenney** [emgucv/emgucv#389]
![error](https://user-images.githubusercontent.com/5629942/101592512-3cf3df80-39a3-11eb-8853-5cd0187677dc.png)

Built with a command:
dotnet publish MyProj.csproj -c Release -f net5.0-windows -r win10-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

The app builds and starts up, but fails during during initialization since EmguCV uses some functions disallowed in single-file applications.

**Comment by emgucv** [comment]
You are right. Looking at the documentation here:
https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file

Assembly.CodeBase is incompatible with Single file deployment. It will throw exception in single file deployment.

We will remove CodeBase usage from the source code.

**Comment by JohnTenney** [comment]
With the new 4.5.1 version (commercial license), I just tried again with a single-file executable and got the following error in the event viewer (the app never launched):

Description: A .NET application failed.
Application: ImageAnalyzer.exe
Path: C:\Temp\ImageAnalyzer.exe
Message: Error:
  An assembly specified in the application dependencies manifest (ImageAnalyzer.deps.json) was not found:
    package: 'Emgu.CV.runtime.windows.dldt', version: '4.5.1.4349'
    path: 'runtimes/win-x64/native/plugins.xml'

I used the following settings on 'dotnet publish':
 -c Release -f net5.0-windows -r win10-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

Can you verify that you can build a single-file executable with an Emgu app?

**Comment by emgucv** [comment]
I think .net5.0-windows may not support single file publish. 

I have tried to create a blank project **without** using Emgu CV at all, using the following steps:

1. Create a new project using the template: Windows Forms APP (.NET). 
2. Upgrade the .Net framework from .net core 3.1 to net5.0-windows
3. Do not add any nuget pacakges, just the project from template.
4. Compiles with your script 
`dotnet publish -c Release -f net5.0-windows -r win10-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true` 
from power shell.
5. Run the compiled application. App never launch. Got the following error in the event viewer:

Application: WindowsFormsApp2.exe
CoreCLR Version: 5.0.220.61120
.NET Version: 5.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at System.Reflection.RuntimeModule.GetFullyQualifiedName()
   at System.Reflection.RuntimeModule.get_Name()
   at System.Windows.Forms.Application.EnableVisualStyles()
   at WindowsFormsApp2.Program.Main()

**Comment by JohnTenney** [comment]
This seems to work in .NET 6 preview 2. So I think the problem may be solved on MSFT's side...
dotnet publish MyProj.csproj -c Release -f net6.0-windows -r win10-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
