### ISSUE TITLE
Build support for VS2017

### ISSUE THREAD

**Issue by bernd5** [emgucv/emgucv#46]
Hi, it would be nice to have build support for vs2017, currently it fails

**Comment by Mikhail158** [comment]
Can you please post your error here? Everything is working fine for me.

**Comment by bernd5** [comment]
Okay, perhaps it is a CMake problem. I get the error message:
"Could not create named generator Visual Studio 12 2005"

**Comment by emgucv** [comment]
If you need to use the scripts in the "platforms/windows" folder to build the native binary with Visual Studio 2017, you can use a text editor to open up the "Build_Binary_x86.bat" file, find the following line in the file:

> REM IF EXIST %VS2017% SET DEVENV=%VS2017%

and change it into

> IF EXIST %VS2017% SET DEVENV=%VS2017%

That will let you generate Visual Studio 2017 solutions for the native binary. 

Our release are build with Visual Studio 2015, the reason is that, the GPU build requires CUDA SDK, and CUDA SDK do not support VS2017. We want to use the same Visual Studio release for all builds and therefore the build script will only search for Visual Studio up to 2015.

**Comment by bernd5** [comment]
See my pull request...

**Comment by bernd5** [comment]
I adjusted the build script again, in general we shouldn't skip devenv detection but write some error message if the detected devenv is incompatible with some settings (like CUDA...)

**Comment by goodtogood** [comment]
actually cuda9 rc has been released, it does support vs2017.

**Comment by cwule** [comment]
When building with cmake (I tried both VS 2015 & 2017) I get the error:
CMake Error at Emgu.CV.Extern/CMakeLists.txt:1531 (IF):
  if given arguments:

    "(" "GREATER" "5" ")" "OR" "(" "(" "STREQUAL" "5" ")" "AND" "(" "GREATER" "0" ")" ")"

Looking at the CMakeLists.txt it seems that this variable ${npp_major} is empty.

**Comment by emgucv** [comment]
CUDA 9 final release is also out. We tried but CUDA 9 is not compatible with Open CV v3.3. Compiling Open CV with CUDA 9 and VS2017 result in several different errors. We will wait for Open CV to officially support CUDA 9 before moving to VS2017.

**Comment by emgucv** [comment]
Implemented a few workarounds and got CUDA 9, VS2017 working with Open CV 3.3. The Emgu CV 3.3 release will be built with VS2017 and CUDA 9.

**Comment by goodtogood** [comment]
great!
