### ISSUE TITLE
Failed to build x86

### ISSUE THREAD

**Issue by ChengYen-Tang** [emgucv/emgucv#495]
Hi,
I want to build gstreamer + emgucv together. The compilation for the x64 platform can be successfully build, but the package parameter must be used to generate opencv_videoio_gstreamer451_64.dll.
When compiling on the x86 platform, if the package parameter is used, the following error will occur.
`LINK : fatal error LNK1181: cannot open input file 'freetype.lib' [D:\agent\_work\1\s\build_x86\Emgu.CV.Extern\cvextern
.vcxproj]`

**Comment by emgucv** [comment]
It looks like you have a emgucv build issue with freetype. If you don't really use freetype, you can set the emgu cv build flag "EMGU_CV_WITH_FREETYPE" to "FALSE".

Another way is to build "opencv_videoio_gstreamer451.dll" based on the open cv source code (instead of Emgu CV), generate the dll file and then drop then into the prebuild emgu cv binary, that should work too.
