### ISSUE TITLE
CUDA not working

### ISSUE THREAD

**Issue by Watearth** [emgucv/emgucv#523]
Hello,

When I try to code with cuda, it doesn't work...

When I check for opencl :
System.Windows.Forms.MessageBox.Show(CvInvoke.OclGetPlatformsSummary()); 
![image](https://user-images.githubusercontent.com/85670890/121486534-831d1080-c9d1-11eb-80ca-096cdeb4bf21.png)

When I check for CUDA : 
System.Windows.Forms.MessageBox.Show(CudaInvoke.GetCudaDevicesSummary()); 
![image](https://user-images.githubusercontent.com/85670890/121486566-8b754b80-c9d1-11eb-9d10-282d2edcfbad.png)

When I try to have DeviceID with : 
int ID = CudaInvoke.GetDevice();

In Output I have this message :
"Open CV error at file D:\bb\cv_x64\build\opencv\modules\core\include\opencv2/core/private.cuda.hpp, line 106, function throw_no_cuda: The library is compiled without CUDA support"

It is not normal because I use DLL generate with cuda version of EMGU CV : 
"libemgucv-windesktop_x64-cuda-4.5.1.4349.zip.selfextract.exe"

Can you help me please?

**Comment by Watearth** [comment]
Hello I try with full github source and generate it with cuda but no change...

**Comment by emgucv** [comment]
You should call the CvInvoke.BuildInformation to check the native binary info. 

It looks like that your application is using the non-cuda version of the runtime. 

If you type "dotnet run" under the extracted folder "Emgu.CV.Example/BuildInfo.NetCore.Console" from the "libemgucv-windesktop_x64-cuda-4.5.1.4349.zip.selfextract.exe" package. The BuildInfo looks like the following:
![image](https://user-images.githubusercontent.com/2035816/121546304-2faec080-c9d9-11eb-864f-558f709b1699.png)

The build path is "D:/bb/cv_x64_cuda". 

The fact that your error message says:
`"Open CV error at file D:\bb\cv_x64\build\opencv\modules\core\include\opencv2/core/private.cuda.hpp, line 106, function throw_no_cuda: The library is compiled without CUDA support"`
indicates that the build path is "cv_x64", which is the binary from the non-cuda build.

You are using the non-cuda version of the binary instead of using the cuda version from "libemgucv-windesktop_x64-cuda-4.5.1.4349.zip.selfextract.exe" package.

**Comment by Watearth** [comment]
Hello,

I restart my project with no nuget element and direct dll from cuda version download.

it is work now!

I have a new problem with 'CudaInvoke.Phase' with error message 'OpenCV: x.depth() == CV_32F' but I have check that.

**Comment by Watearth** [comment]
I have resolve my issue ! Now it's work !
