### ISSUE TITLE
Emgu.CV.Util.CvException:“OpenCV: u != 0”

### ISSUE THREAD

**Issue by boyucjz** [emgucv/emgucv#545]
public static void PreprocessImage(Mat image)
 {
      // 计算角度
      Image<Gray, byte> imgGrey = new Image<Gray, byte>(image.Size);
      double low = 70.0, high = 210.0;
      CvInvoke.Canny(image, imgGrey, low, high, 3);
      double degree = CalcDegree(ref imgGrey);
      imgGrey.Dispose();

      // 旋转图片
      Image<Rgb, byte> imgRgb = new Image<Rgb, byte>(image.Size);
      image.CopyTo(imgRgb);
      imgRgb=imgRgb.Rotate(degree, new Rgb(255, 255, 255));
      imgRgb.Mat.CopyTo(image);
      imgRgb.Dispose();
}

When executing the above function，an error is reported here ：  “CvInvoke.Canny(image, imgGrey, low, high, 3);”
Error information： Emgu.CV.Util.CvException:“OpenCV: u != 0”

EMGU版本：3.1.0.2504

Running in x86 mode

**Comment by emgucv** [comment]
version 3.1.0 was released in 2016-02-06 and is no longer supported. Please upgrade to the latest version.

"u!=0" error means open cv failed to allocate the memory for the image during the Canny function call. This could be due to many reasons. Check the input images to make sure it is valid. 

One of the many possible reasons I can think of is that "Mat image" is empty when passed to the function.

**Comment by emgucv** [comment]
Another possible reason is that system run out of memory during the process. You do mention that it is run in "x86" mode. I believe only a maximum of 2GB of memory region is provided for the x86 program.
