### ISSUE TITLE
libemgucv-android 3.2 build issue

### ISSUE THREAD

**Issue by amdlopes** [emgucv/emgucv#64]
Hello

We have commercial license for 3.2 and im trying to build the android component to evaluate.

I have Xamarin Studio 6.2 (build 1821) and Xamarin.Android 7.3.1.2 (Xamarin Studio Community).

I am getting immediate build fail (either XS or mdtool) with:

.../work/Others/EmguCV_3.2/libemgucv-android/Emgu.CV.World/Emgu.CV.World.Android.csproj: Unable to evaluate condition "$(AndroidSupportedAbis.Contains('armeabi%3')) OR $(AndroidSupportedAbis.Contains('armeabi,')) OR $(AndroidSupportedAbis.Contains('armeabi;')) OR $(AndroidSupportedAbis.EndsWith('armeabi')) OR ('$(AndroidSupportedAbis)'=='' AND '$(Platform)'=='AnyCPU') OR ('$(Platform)'=='armeabi')" : Expression "$(AndroidSupportedAbis.Contains('armeabi;'))" evaluated to "$(AndroidSupportedAbis.Contains('armeabi;'))" instead of a boolean value

Is there a minimum version for Xamarin.Android/Xamarin Studio to be able to build libemgucv-android 3.2?

Thanks!

**Comment by amdlopes** [comment]
Unfortunately we can't (yet) upgrade to VS due to business restrictions.
I'll try to do it in a VM or sandbox machine of some sort.

Can you confirm if it will only build by VS though or latest XS will do too?

**Comment by emgucv** [comment]
Hi, 

I can confirm that the Emgu CV for Xamarin Android v3.2 release can be build with:
  _Visual Studio Community 2017 for Mac, Version 7.2 (build 636)_
But will have build errors as you pointed out with:
  _Xamarin Studio 6.3 (build 864)._

As a note from Xamarin's web page:
https://developer.xamarin.com/releases/studio/xamarin.studio_6.3/xamarin.studio_6.3/

Xamarin Studio 6.3 is the final release of Xamarin Studio. It is replaced with Visual Studio for Mac.

If you are not allowed to upgrade to Visual Studio for Mac, you can still use the pre-compiled Emgu.CV.World.Android.dll included in the release package with Xamarin Studio, by adding it as a reference of your project. You will not able to compile the Emgu.CV.World.Android.dll from source due to a bug in Xamarin Studio 6.3.

**Comment by amdlopes** [comment]
Thanks,

I've build this using a different machine with latest VS for Mac and updated xamarin environment (latest releases of Xamarin Android and Xamarin iOS). I can confirm Emgu CV for Xamarin Android v3.2 can only be build with VS for Mac.

Closing the ticket.
