### ISSUE TITLE
What is type Point?

### ISSUE THREAD

**Issue by ahyow** [emgucv/emgucv#650]
Hi, want to ask in emgucv/Emgu.CV.Contrib/StructuredLight/GrayCodePattern.cs 
line 82

the return is Point?

May i know why is Point? not just Point??

**Comment by ahyow** [comment]
For your information i here to attach the picture 
![image](https://user-images.githubusercontent.com/45448398/141883514-76b3ff6f-2cec-4965-9d3e-0e418998e919.png)


thank you in advance!

**Comment by emgucv** [comment]
Is the questions about if the return type should be "Point?" or "Point"?

For return type of "Point", it cannot be "null" becasuse "Point" is a structure. For return type of "Point?", it can be "null".

In this particular function, if the projPixel is not found, "null" is returned. If it is found, the actual point is returned. We need an option to return "null", and therefore the return type is "Point?" (instead of "Point")

For detail please see this:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types

**Comment by ahyow** [comment]
Ah thank you so much for reply, definitely answer my question and it so clear to understand!
