### ISSUE TITLE
[BUG] Mat.GetData does not respect the ROI

### ISSUE THREAD

**Issue by JPasterkampRotec** [emgucv/emgucv#834]
**Describe the bug**
The `Mat.GetData(bool jagged)` method does not return the expected values when the Mat was constructed with `Mat(Mat mat, Rectangle roi)`.

**OS / Platform**
Windows 10

**.Net version**
.NetFramework 4.8

**CPU Architecture**
x64

**Emgu CV package used**
Emgu.CV nuget package 4.6.0.5131
Emgu.CV.Bitmap nuget package 4.6.0.5131
Emgu.CV.runtime.windows nuget package 4.6.0.5131

**To Reproduce**
As an example I'm creating a 3x3x3 Mat with fixed values (x = 1 to 9, y = 10 to 90, z = 100  to 900):
```csharp
const int WIDTH = 3;
const int HEIGHT = 3;
float[] x = new float[WIDTH * HEIGHT], y = new float[WIDTH * HEIGHT], z = new float[WIDTH * HEIGHT];

for (int i = 0; i < WIDTH * HEIGHT; i++)
{
	x[i] = (i + 1);
	y[i] = (i + 1) * 10;
	z[i] = (i + 1) * 100;
}

Mat xChannel, yChannel, zChannel;
unsafe
{
	fixed (float* pointerX = x)
	fixed (float* pointerY = y)
	fixed (float* pointerZ = z)
	{
		xChannel = new Mat(HEIGHT, WIDTH, DepthType.Cv32F, 1, (IntPtr)pointerX, 0);
		yChannel = new Mat(HEIGHT, WIDTH, DepthType.Cv32F, 1, (IntPtr)pointerY, 0);
		zChannel = new Mat(HEIGHT, WIDTH, DepthType.Cv32F, 1, (IntPtr)pointerZ, 0);
	}
}

var xyzMat = new Mat(HEIGHT, WIDTH, DepthType.Cv32F, 3);
CvInvoke.Merge(new VectorOfMat(xChannel, yChannel, zChannel), xyzMat);
```

The `xyzMat` is clipped with a region of interest:
```csharp
var clippedMat = new Mat(xyzMat, new Rectangle(1, 1, 2, 2));
```

------------------------------------------------------------------------------

**Now we want to get the flat [ x, y, z, x, y, z, etc.] float array from the `clippedMat`. The correct result is:
[ 5, 50, 500, 6,  60, 600, 8, 80, 800, 9, 90, 900 ]**

👍 When using `Mat.GetRawData()` and manually mapping the bytes back to floats, the `rawFloats` will be equal to the correct result.
```csharp
byte[] rawBytes = clippedMat.GetRawData();
// This will be (after block copy) [ 5, 50, 500, 6, 60, 600, 8, 80, 800, 9, 90, 900 ].
float[] rawFloats = new float[rawBytes.Length / sizeof(float)];
Buffer.BlockCopy(rawBytes, 0, rawFloats, 0, rawBytes.Length);
```

👎 However, when using `Mat.GetData(bool jagged)`, the `directFloats` will not be equal to the correct result.
```csharp
// This will be [ 5, 50, 500, 6, 60, 600, 7, 70, 700, 8, 80, 800 ].
float[] directFloats = (float[])clippedMat.GetData(jagged: false);
```

**Expected behavior**
I expect `Mat.GetData(bool jagged)` to return the same results as `Mat.GetRawData()`, even when the Mat is clipped with a ROI.

**Additional context**
I suspect this is caused by the internal copying mechanisms that the 2 methods use. 
`Mat.GetRawData()` uses `MatInvoke.cveMatCopyDataTo`, which actually respects the ROI. 
`Mat.GetData(bool jagged)` uses `CvInvoke.cveMemcpy`, which does not respect the ROI.

**Comment by sn4k3** [comment]
`Mat(roi)` uses the data from parent `Mat` with a `IntPtr` advanced to match first pixel of the Roi, but it stills uses same data memory. So, it's normal what you see with `GetData`, you would observe same when using direct memory access with a Span.

To solve your problem you can do:

1. `mat.Clone()` This will clone roi mat with the correct data, then you can do `roiMat.GetData` and get what you want
2. Use a `Span2D`

**Comment by JPasterkampRotec** [comment]
> `Mat(roi)` uses the data from parent `Mat` with a `IntPtr` advanced to match first pixel of the Roi, but it stills uses same data memory. So, it's normal what you see with `GetData`, you would observe same when using direct memory access with a Span.

I disagree, when you create a Mat with constructor `Mat(Mat mat, Rectangle roi)` you expect it to share memory, but you don't expect to get data outside the ROI.
One indicator is that `Mat.GetData(bool jagged)` returns the exact length of the ROI, indicating that **the original intention of the code is to only pass back the data inside the ROI**. It even starts at the exact start position of the ROI!

> 
> To solve your problem you can do:
> 
> 1. `roiMat.Clone()` This will clone roi mat with the correct data, then you can do `roiMatCloned.GetData` and get what you want
> 2. Use a `Span2D`

Thank you for providing some workarounds, I had been using the `Mat.GetRawData()` to get only the ROI data for now.
Both our workarounds are less memory-efficient than if `Mat.GetData(bool jagged)` would work properly.
**However, even if there were memory-efficient workarounds, this is still a bug.**

**Comment by sn4k3** [comment]
Is true that Mat(roi) have some misleading methods and return data/info from original mat. Reading `Mat.cs ` is recommended to understand what you will get.
I would not brother much with that data thing because all it's methods to access data are very slow and not efficient. The only way to get performance is to use C# `Span` which give you direct access to data memory and allow you to get/set pixels with the highest performance without require a copy.

When you do GetData you will get a copy, if data is 1gb you will take an additional 1gb to ram. With span you get almost "0" ram to manipulate the data. No matter if is read or write it will always be fastter than using Mat methods.

For your case you need to use `Span2D` which will only capture a region (Rectangle / Roi)

I have created a bunch of [extensions](https://github.com/sn4k3/UVtools/blob/master/UVtools.Core/Extensions/EmguExtensions.cs) to handle with data correctly and with extras. See [GetDataSpan2D](https://github.com/sn4k3/UVtools/blob/master/UVtools.Core/Extensions/EmguExtensions.cs#LL200C36-L200C49) When calling matRoi.GetDataSpan2D<type>() it will return a Span2D with direct access to it pixels only matching the region. Also it eliminate the casting required by mat.GetData

**Comment by JPasterkampRotec** [comment]
> Is true that Mat(roi) have some misleading methods and return data/info from original mat. Reading `Mat.cs` is recommended to understand what you will get. 

You shouldn't have to read the implementation code to understand the intention of a method. In this case it required me to read some parts of `Mat.cs` to understand the bug.

Thank you for sharing the extensions, I will be using [GetDataSpan](https://github.com/sn4k3/UVtools/blob/5ab1f1e71cc0a653db19fe5938f2171c6adafd68/UVtools.Core/Extensions/EmguExtensions.cs#L235) to get the data in a memory-efficient way.

**Comment by sn4k3** [comment]
> You shouldn't have to read the implementation code to understand the intention of a method. In this case it required me to read some parts of Mat.cs to understand the bug.

That's true, however if you writing high-performance applications or if that's matter you should always peek the method, because we never know how methods are making stuff, also C# is known to have lot of protections before do actions, a getter/setter is often not just an getter/setter... For example see [Span2D indexer](https://github.com/CommunityToolkit/dotnet/blob/v8.2.0/src/CommunityToolkit.HighPerformance/Memory/Span2D%7BT%7D.cs#L650C43-L663) you may think: "ah span[x,y] is just returning my value without any other operation" -- Wrong, you have a if checking for bounds, and why we need an extra operation when we always know we are inside bounds? Luckly, they offer an extension to allow direct access without the **if** (`span.DangerousGetReferenceAt`). It's minor but after millions of iterations if's costs time and we already defined bounds on the x,y for's. Normal `Span` also have same if check. So in C# is very important to have a peek at methods if performance matters.

> GetDataSpan2D even throws an ArgumentOutOfRangeException for the pitch parameter when constructing the Span2D.

My methods are written for Mat with bytes (8U), I never tried for float's, I guess the problem is `/ mat.ElementSize` or on step calculation, you should make a breakpoint on that line and verify what is wrong. Try to remove `/ mat.ElementSize` first and see how it does

**Comment by JPasterkampRotec** [comment]
> **Edit:** I wrote a small test and GetDataSpan2D worked fine for float's

The reason why it's not working for my example code is probably because I'm creating a 3x3x3 `Mat` (3 layers), which is not working with the `GetDataSpan2D`. I assume it only works for a one layer `Mat`, usually gray images or masks.

------------------------------------------------

I appreciate your help, but we are getting very off-topic here. This started with a bug in `Mat.GetData(bool jagged)` and now we are discussing more performant ways of getting `Mat` data and potential bugs in other GitHub repositories 😁.

Let's stay within the confines of this issue, which is about `Mat.GetData(bool jagged)` not respecting the ROI.

**Comment by sn4k3** [comment]
> The reason why it's not working for my example code is probably because I'm creating a 3x3x3 Mat (3 layers), which is not working with the GetDataSpan2D. I assume it only works for a one layer Mat, usually gray images or masks.

Ok, it really has a bad pitch for those cases, I have fixed to work with everything now: 
```C#
return new(mat.DataPointer.ToPointer(), mat.Height, step, mat.Step / mat.ElementSize * mat.NumberOfChannels - step);
```

Test: 
```C#
        var mat = new Mat(new Size(100, 100), DepthType.Cv32F, 3);
        var matRoi = new Mat(mat, new Rectangle(9, 9, 10, 10));
        mat.SetTo(EmguExtensions.BlackColor);
        var span = mat.GetDataSpan2D<float>();
        var spanRoi = matRoi.GetDataSpan2D<float>();
        span.Fill(50);
        spanRoi.Fill(255);

        // Lets set all 4 corner RED
        // TL
        spanRoi[0,0] = 000; // B
        spanRoi[0,1] = 000; // G
        spanRoi[0,2] = 255; // R

        // TR
        spanRoi[0, 9 * 3 + 0] = 000; // B
        spanRoi[0, 9 * 3 + 1] = 000; // G
        spanRoi[0, 9 * 3 + 2] = 255; // R

        // BL
        spanRoi[9, 0] = 000; // B
        spanRoi[9, 1] = 000; // G
        spanRoi[9, 2] = 255; // R

        // BR
        spanRoi[9, 9 * 3 + 0] = 000; // B
        spanRoi[9, 9 * 3 + 1] = 000; // G
        spanRoi[9, 9 * 3 + 2] = 255; // R

        mat.Save("D:\\test.png");
```

Results in:

![image](https://user-images.githubusercontent.com/113281/236003139-12acf04b-b2b2-4bdf-aaf5-5a617b3a3572.png)

> Let's stay within the confines of this issue, which is about Mat.GetData(bool jagged) not respecting the ROI.

Fair enough, let @emgucv review this case.

**Comment by emgucv** [comment]
We are looking into the issues. Will get back to you in a day or two.

**Comment by emgucv** [comment]
Should have been fixed in the above commit. We also added an additional unit test to check.

**Comment by sn4k3** [comment]
`Step` and I guess `Total` also suffer from same, where the returned value is from original Mat.
Also, would be super useful if Mat can have a `Root` property which always point for original `Mat` when Mat(mat, roi) is used.
eg:

```C#
class Mat
{
   Mat? Root {get; set;} = null;

   public Mat(Mat mat, Rectangle roi)
   {
        // If the mat already has a root, means is a roi of a roi, otherwise is the root mat.
        this.Root = mat.Root ?? mat;
        
        // Alternative:
        this.Root = mat.IsSubMatrix ? mat.Root : mat;
    }
}
```

**Comment by JPasterkampRotec** [comment]
@emgucv I read the commit and I think that it solves the issue 😀. 
I did however add a comment to the unit tests of commit https://github.com/emgucv/emgucv/commit/993edfb76afa1adcc3a4d7086f5148ab761bbf6c.

**Comment by onslauth** [comment]
@sn4k3 is it possible to use `GetDataSpan` on `roi` to get 1d span?

**Comment by JPasterkampRotec** [comment]
I just checked this on the new version (4.8) and now it works properly.
Thanks everyone for helping me out!
