### ISSUE TITLE
Emgucv 3.3.x does not find cuda 9.0

### ISSUE THREAD

**Issue by LingboTang** [emgucv/emgucv#87]
Hi team,

I got libemgucv-windesktop_x64-cuda-3.3.0.2826.exe from sourceforge, and I also installed EmguCV 3.3.0.2826 in my visual studio project through nuGet package manager. I have Cuda 9.0.176 on latest windows 10 machine installed. When I tried to call `CudaInvoke.HasCuda`  it still returns `false`. According to http://www.emgu.com/wiki/index.php/Download_And_Installation, I don't think I need to manually add reference for my project. What am I missing to configure Cuda with emgucv for the latest version?

**Comment by LingboTang** [comment]
I also added reference from `emgucv-windesktop_x64-cuda 3.3.0.2826\bin` and `\emgucv-windesktop_x64-cuda 3.3.0.2826\bin\x64` to my visual studio 2017 project. I don't know why it still can't find cuda.

**Comment by LingboTang** [comment]
And my `CudaInvoke.GetCudaEnabledDeviceCount()` returns 0, which is weird, because if I added opencv dlls that compiled with Cuda as reference, I should get a non-zero device count. I've read some post about this simillar issue, it seems it only happens when you are using the opencv *.dlls that does not compile with Cuda.

**Comment by LingboTang** [comment]
I don't think the package I downloaded from nuGet package manager has cuda support. Please add a version that support cuda in nuGet Gallery.

**Comment by LingboTang** [comment]
I have to copy those `*.dlls` manually from `emgucv-windesktop_x64-cuda 3.3.0.2826\libs\` mainly `concrt140.dll`, `cvextern.dll`, `msvcp140.dll`, `opencv_ffmepg330_64.dll` and `vcruntime140.dll`.

**Comment by emgucv** [comment]
FYI, if the emgu cv release package do not contains "cuda" or "gpu" in its package name, it is build without CUDA support, and CudaInvoke.HasCuda will always return false. 

Only those release packages that contain "cuda" or "gpu" in the package name are built with CUDA support.

The nuget.org repository do not contains Emgu CV release that supports GPU. The reason is that our GPU release has file size that exceed the package size limit of 250 MB set by nuget.org. An Emgu CV nuget package with GPU support is around 320MB in size.

If you need to use Emgu CV with GPU support, you can download the ".zip" or ".exe" package from sourceforge. If you have an Emgu CV commercial license, you can also download our Emgu CV GPU commercial Nuget packages hosted on "myget.org" that can support larger file size limit. 

Hope that answer your questions. 

Best regards,

Canming

**Comment by emgucv** [comment]
You can also try to upgrade your NVidia Graphic card driver to the latest version. If the graphic card driver version is older than the CUDA runtime's support version , CudaInvoke.HasCuda will also return false.

**Comment by LingboTang** [comment]
Well I have Cuda 9.0 as listed, and in your 3.3 release note, your team just claimed that it just started to support Cuda 9.0.

**Comment by emgucv** [comment]
I am referring to the NVidia Graphic Card driver, e.g. my current driver version for my GTX 1080 is version "390.65". If you have a driver older than this version, and Emgu CV is not able to find your CUDA graphic card, try upgrading the driver to at least version 390.65. 

If the graphic card driver is older than the CUDA runtime it supports,  Emgu CV / Open CV will report "false" when you call "CudaInvoke.HasCuda". 

There is no need to install CUDA at all at the workstation that use Emgu CV's CUDA build, because all the required CUDA runtime files is included in the Emgu CV "bin\x64" folder. Emgu CV v3.3 CUDA release is compiled with CUDA 9.0 and the CUDA 9.0 runtime is included in the "bin\x64" folder of the cuda compatible release package. You should find a "cudart64_90.dll" file in side that folder in the cuda build.

**Comment by emgucv** [comment]
If you are still having issue. Please let me know the type of Graphic Card you are using, the Nvidia Graphic card driver version and the OS type. 

Another note, CUDA 9.0 only support Compute version higher or equals to v3.0. You will need a Nvidia GTX 7xx series or newer graphic card to run in GPU mode.

**Comment by LingboTang** [comment]
I'm manually adding the reference to the GPU version and it all works. I'm not having this problem any more, but just a suggestion that GPU version should be visible on nuGet somehow, or if your team want to commercialize the GPU version, please provide an explicit link. I'm closing this ticket now.

**Comment by rigoletiny** [comment]
Where did you reference the GPU version?

**Comment by LingboTang** [comment]
@rigoletiny You can find the GPU version on the official documentation page: http://www.emgu.com/wiki/index.php/Version_History. You can also check the CUDA release notes here: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

**Comment by SMA2016a** [comment]
Hi Lingbo,

I have the same issue, would you tell me which dlls need to be add? or how you have fix the issue,please?
