### ISSUE TITLE
[EXCEPTION] Exception using CudaORBDetector DetectAndCompute

### ISSUE THREAD

**Issue by ShaggyHW** [emgucv/emgucv#885]
**Describe the bug**
using CudaORBDetector to get the descriptors of an image, throws the following expection:

`Emgu.CV.Util.CvException: 'OpenCV: image.type() == CV_8UC1'`

I'm 99% sure this is just me messing up something.

** OS / Platform **
Windows

** .Net version **
.Net 7

**CPU Architecture**
e.g. x86_64, ARM64, x86

** Emgu CV package used**
Most recent cuda npkg

**To Reproduce**
`   CudaORBDetector ORB = new CudaORBDetector();

    var preMat = Emgu.CV.CvInvoke.Imread(file); // Image2 now have the details of second image 

    GpuMat Image2 = new GpuMat();

    Image2.Upload(preMat);           

    VectorOfKeyPoint KeyPoints2 = new VectorOfKeyPoint(); 

    GpuMat Descriptors2 = new GpuMat();         

    //Feature Extraction from Image2

    ORB.DetectAndCompute(Image2, null, KeyPoints2, Descriptors2, false);
`

**Expected behavior**
It should return the descriptors for the image

**Screenshots**
![imagem](https://github.com/emgucv/emgucv/assets/20775207/aff44743-9caa-431e-a425-8898589d435a)

**Additional context**
Any help solving this issue would be very apreciated

**Comment by emgucv** [comment]
The error message ('OpenCV: image.type() == CV_8UC1') says that ORB feature extractor can only handle gray scale image. You are passing a BGR image and that is why it fails. You can convert the image from BGR to Grayscale before passing it to the DetectAndCompute function.

Beside of that, if a function is not under the Cuda namespace, it won't be using CUDA for computation, there may be additional transfer to the CUDA gpu if you pass GpuMat to those functions and make it slower. If you want to test using the GPU for those function, you can try so by using OpenCL, in which case, you should use UMat instead of GMat.
