### ISSUE TITLE
Import Blob Image to Neural Net

### ISSUE THREAD

**Issue by luketg8** [emgucv/emgucv#9]
hi,

I have been experimenting with the new tensorflow importer and have had the issue when trying to import an image to test my neural net with

`CvInvoke.Resize(image, image, size);

                CvInvoke.CvtColor(image, image, Emgu.CV.CvEnum.ColorConversion.Bgr2Rgb);

                Blob input = new Blob(image);

                net.SetBlob(".input", input);

                net.Forward();`

I have had the issue where it cannot import the input blob image as "OpenCV: input.dims() == 4 && (input.type() == CV_32F || input.type() == CV_64F)"

I have looked it up and this is due to this issue https://github.com/opencv/opencv_contrib/issues/749

Is there an alternate way of achieving this?

**Comment by emgucv** [comment]
Hi,

Thanks for the report. The issue has been fixed in the Git master. 

Apparently it requires a new API that is not wrapped in the 3.1 release. It is added now. Dnn.Blob.BatchFromImages function call is required to convert the open cv image format to the correct Blob format.

You can make a development build from the source, or if needed, I can make a development build for you.

**Comment by luketg8** [comment]
Thank you!

I had done some further research and had found that this was the case, I really appreciate this fix though.

I am fine to make my own build from source though.

**Comment by luketg8** [comment]
Thank you!

I had done some further research and had found that this was the case, I really appreciate this fix though.

I'm happy to make a build from source.
